### ISSUE TITLE
distro version error in packages

### ISSUE THREAD

**Issue by GarretSidzaka** [GarretSidzaka/docker-conanexiles#2]
got error on build

**Comment by GarretSidzaka** [comment]
[conanbuilderror.txt](https://github.com/user-attachments/files/17608687/conanbuilderror.txt)

**Comment by acelan** [comment]
apt-add-repository ppa:cybermax-dexter/sdl2-backport
This line is redundent, noble provides libsdl2 v2.30, and the ppa doesn't support noble and only contains v2.24.
This could be removed safely.

https://ppa.launchpadcontent.net/cybermax-dexter/sdl2-backport/ubuntu/pool/main/libs/libsdl2/
